/**
 * =============================================================================
 * FILE: spi_driver.h
 * =============================================================================
 *
 * WHAT IS THIS FILE?
 * ------------------
 * This is the PUBLIC INTERFACE of our SPI driver.
 * A header file (.h) is like a "menu" or "contract":
 *   - It declares WHAT exists (types, functions, constants)
 *   - It does NOT say HOW things work (that's in the .c file)
 *   - Any file that wants to USE the SPI driver just includes this header
 *
 * ARCHITECTURE OVERVIEW
 * ---------------------
 * We have a layered design. Think of it as floors in a building:
 *
 *   [ main.c / ads1220_driver.c ]   <- your application code, top floor
 *            |
 *            | calls SPI_Transfer(), SPI_InitBus(), etc.
 *            v
 *   [ spi_driver.h / spi_driver.c ] <- THIS layer, middle floor
 *            |
 *            | calls HAL_SPI_Transmit(), HAL_GPIO_WritePin(), etc.
 *            v
 *   [ STM32 HAL / hardware ]        <- bottom floor, hardware reality
 *
 * WHY LAYERS?
 * -----------
 * - Each layer only talks to the one directly below it
 * - If you switch from STM32 to another MCU, you ONLY change the
 *   bottom of spi_driver.c — nothing in main.c or ads1220_driver.c changes
 * - Each layer is independently testable
 *
 * HOW MULTIPLE FILES USE THIS HEADER
 * ------------------------------------
 * Both main.c and ads1220_driver.c will have:
 *   #include "spi_driver.h"
 * That gives them access to all the types and function declarations below.
 *
 * =============================================================================
 */

/* -----------------------------------------------------------------------------
 * HEADER GUARD
 * -----------------------------------------------------------------------------
 * Problem: if two .c files both include this header, and one of them also
 * includes the other, this file could get included TWICE in one compilation.
 * That causes "redefinition" errors.
 *
 * Solution — the header guard:
 *   1. First time this file is included: SPI_DRIVER_H is not defined yet,
 *      so we enter the #ifndef block and define SPI_DRIVER_H.
 *   2. Second time this file is included: SPI_DRIVER_H is already defined,
 *      so the #ifndef is false → the entire file is skipped.
 *
 * Rule: always name the guard after the filename, all caps, dots → underscores.
 * Never use leading double-underscore (__) — those are reserved by the C standard.
 * ----------------------------------------------------------------------------- */
#ifndef SPI_DRIVER_H
#define SPI_DRIVER_H

/* -----------------------------------------------------------------------------
 * INCLUDES
 * -----------------------------------------------------------------------------
 * <stdint.h>  — gives us uint8_t, uint16_t, uint32_t, int32_t, etc.
 *               These are "fixed-width" integer types.
 *               Without this, "int" could be 16 or 32 bits depending on the
 *               compiler and MCU — very dangerous in embedded systems.
 *               With uint8_t you KNOW it is always exactly 8 bits.
 *
 * "main.h"    — generated by CubeMX, contains the STM32 HAL includes and
 *               the GPIO pin definitions (GPIO_PIN_4, GPIOA, etc.)
 *
 * "spi.h"     — generated by CubeMX, contains extern declarations for the
 *               SPI handles: hspi1, hspi3, etc.
 *               A "handle" in STM32 HAL is a struct that holds all the
 *               state for one SPI peripheral. HAL functions take a pointer
 *               to it: HAL_SPI_Transmit(&hspi1, ...)
 * ----------------------------------------------------------------------------- */
#include <stdint.h>
#include "main.h"
#include "spi.h"

/* -----------------------------------------------------------------------------
 * CONFIGURATION CONSTANTS
 * -----------------------------------------------------------------------------
 * #define creates a compile-time constant — the preprocessor does a
 * text substitution before compilation. No memory is allocated.
 *
 * Putting these here (instead of hardcoding numbers in .c) means:
 *   - You can change SPI_BUS_COUNT from 2 to 3 in ONE place
 *   - Every part of the code that uses it automatically updates
 *   - The number has a meaningful name instead of being a "magic number"
 * ----------------------------------------------------------------------------- */

/* How many physical SPI buses exist on your board.
 * Example: STM32F4 has SPI1, SPI2, SPI3 but maybe you only use 2 of them. */
#define SPI_BUS_COUNT           2

/* Maximum number of slave devices allowed per bus.
 * Example: on SPI1 you have ADS1220 + a flash chip = 2 slaves.
 * Set this to the maximum you'll ever need across all your projects. */
#define SPI_MAX_SLAVES          4

/* Maximum length of a human-readable slave name string.
 * Example: "ADS1220_channel0" is 16 chars — 32 gives comfortable headroom. */
#define SPI_MAX_DESC_LEN        32

/* How many milliseconds to wait for HAL to finish a transfer before giving up.
 * 100ms is very generous for SPI — typical transfers take microseconds.
 * If you get SPI_TIMEOUT errors, something is electrically wrong. */
#define SPI_DEFAULT_TIMEOUT_MS  100


/* =============================================================================
 * ENUMS (Enumerated Types)
 * =============================================================================
 * An enum gives names to a set of integer constants.
 *
 * WHY USE ENUMS INSTEAD OF #define?
 *   #define SPI_OK    0          <- just text substitution, no type info
 *   #define SPI_ERROR 1
 *
 *   typedef enum { SPI_OK=0, SPI_ERROR=1 } SPI_Status_t;   <- has a TYPE
 *
 * With the enum version, the compiler can warn you if you pass an
 * SPI_Status_t where an SPI_Command_t is expected. With #define it can't.
 * This catches entire classes of bugs at compile time.
 *
 * The "typedef" makes it so you can write:
 *   SPI_Status_t result;        <- clean
 * instead of:
 *   enum SPI_Status result;     <- verbose C syntax without typedef
 * ============================================================================= */

/* --- Return codes --- */
typedef enum {
    SPI_OK      = 0,    /* everything worked                              */
    SPI_ERROR   = 1,    /* something went wrong (bad pointer, HAL error)  */
    SPI_BUSY    = 2,    /* bus is mid-transfer, try again later           */
    SPI_TIMEOUT = 3     /* HAL waited too long — hardware problem likely  */
} SPI_Status_t;

/* --- Master vs Slave role ---
 * In SPI one device generates the clock (MASTER) and others follow (SLAVE).
 * As a microcontroller talking to a sensor, we are almost always MASTER. */
typedef enum {
    SPI_MODE_SLAVE  = 0,
    SPI_MODE_MASTER = 1
} SPI_MasterSlave_t;

/* --- Clock Polarity (CPOL) ---
 * Defines the idle state of the clock line when no transfer is happening.
 *
 *   CPOL_LOW:  clock idles at 0V   _____|‾|_____
 *   CPOL_HIGH: clock idles at 3.3V ‾‾‾‾‾|_|‾‾‾‾‾
 *
 * Check your sensor's datasheet — it will specify CPOL.
 * ADS1220 datasheet says: CPOL = 0 (clock idles LOW) */
typedef enum {
    SPI_CPOL_LOW  = 0,
    SPI_CPOL_HIGH = 1
} SPI_CPOL_t;

/* --- Clock Phase (CPHA) ---
 * Defines on which clock EDGE data is sampled (captured) vs shifted (output).
 *
 *   CPHA_1EDGE: data is sampled on the FIRST  edge (rising if CPOL=LOW)
 *   CPHA_2EDGE: data is sampled on the SECOND edge (falling if CPOL=LOW)
 *
 * The combination of CPOL + CPHA gives you "SPI Mode":
 *   ┌────────┬──────────┬──────────┬──────────────────────────────┐
 *   │  Mode  │   CPOL   │   CPHA   │  Meaning                     │
 *   ├────────┼──────────┼──────────┼──────────────────────────────┤
 *   │   0    │  LOW(0)  │ 1EDGE(0) │ sample rising, shift falling │
 *   │   1    │  LOW(0)  │ 2EDGE(1) │ sample falling, shift rising │ ← ADS1220
 *   │   2    │  HIGH(1) │ 1EDGE(0) │ sample falling, shift rising │
 *   │   3    │  HIGH(1) │ 2EDGE(1) │ sample rising, shift falling │
 *   └────────┴──────────┴──────────┴──────────────────────────────┘
 *
 * ADS1220 datasheet p.28: "data is clocked out on the falling edge of SCLK"
 * → that means the master must sample on the rising edge AFTER the falling
 *   edge output → CPHA = 2EDGE → Mode 1. */
typedef enum {
    SPI_CPHA_1EDGE = 0,
    SPI_CPHA_2EDGE = 1
} SPI_CPHA_t;

/* --- Transfer direction ---
 * SPI is full-duplex: MOSI and MISO are separate wires, so TX and RX
 * happen simultaneously at the hardware level.
 *
 * But at the software level we often only CARE about one direction:
 *   SPI_CMD_TX:    we send a command, we don't care what the slave sends back
 *   SPI_CMD_RX:    we clock out dummy bytes just to generate clock, reading response
 *   SPI_CMD_TX_RX: we care about BOTH what we send AND what we receive
 *
 * Example with ADS1220:
 *   Sending RESET command   → SPI_CMD_TX    (just send 0x06, ignore response)
 *   Reading conversion data → SPI_CMD_TX_RX (send RDATA command, capture 3 bytes) */
typedef enum {
    SPI_CMD_TX    = 0,
    SPI_CMD_RX    = 1,
    SPI_CMD_TX_RX = 2
} SPI_Command_t;

/* --- Data frame size ---
 * How many bits per "word". Almost always 8-bit for sensors. */
typedef enum {
    SPI_DATASIZE_8BIT  = 0,
    SPI_DATASIZE_16BIT = 1
} SPI_DataSize_t;

/* --- Bit order ---
 * MSB first: bit 7 goes on the wire first (standard, most sensors)
 * LSB first: bit 0 goes first (rare, some niche devices)
 * ADS1220: MSB first */
typedef enum {
    SPI_FIRSTBIT_MSB = 0,
    SPI_FIRSTBIT_LSB = 1
} SPI_FirstBit_t;


/* =============================================================================
 * STRUCTS (Structures)
 * =============================================================================
 * A struct groups related variables together under one name.
 * "typedef struct" lets us use the type name without writing "struct" each time.
 *
 * Think of each struct as a "data package" or "object" in C.
 * We will have three structs forming a hierarchy:
 *
 *   SPI_Bus_t                    ← one per physical SPI bus
 *       └── SPI_Slave_t[]        ← array of slaves connected to that bus
 *
 *   SPI_Transfer_t               ← one per individual transaction (temporary)
 * ============================================================================= */

/* -----------------------------------------------------------------------------
 * SPI_Slave_t — describes ONE physical slave device
 * -----------------------------------------------------------------------------
 * Every IC connected to an SPI bus needs a CS (chip select) pin.
 * When you want to talk to a specific slave, you pull its CS pin LOW,
 * do the transfer, then release CS HIGH. Other slaves ignore traffic
 * when their CS is HIGH.
 *
 * This struct stores everything we need to know about one slave.
 *
 * USAGE EXAMPLE:
 *   // You don't create this directly — SPI_RegisterSlave() fills it for you.
 *   // But conceptually it represents:
 *   //   "There is an ADS1220 on GPIO pin 4, and it is active."
 * ----------------------------------------------------------------------------- */
typedef struct {
    char     descriptor[SPI_MAX_DESC_LEN]; /* Human name: "ADS1220_ch0", "W25Q_flash"
                                            * Used for debugging — you can print it
                                            * to know which slave caused an error      */

    uint16_t cs_gpio_pin;                  /* Which GPIO pin is this slave's CS?
                                            * Example: GPIO_PIN_4
                                            * These are bitmask constants from STM32 HAL:
                                            *   GPIO_PIN_0  = 0x0001
                                            *   GPIO_PIN_4  = 0x0010
                                            *   GPIO_PIN_15 = 0x8000                   */

    uint8_t  active;                       /* Is this slot in use?
                                            * 0 = empty slot (not registered yet)
                                            * 1 = valid slave registered here
                                            * We check this before every transfer to
                                            * catch mistakes like using a freed slot   */
} SPI_Slave_t;


/* -----------------------------------------------------------------------------
 * SPI_Bus_t — describes ONE physical SPI bus
 * -----------------------------------------------------------------------------
 * Your STM32 might have SPI1, SPI2, SPI3. Each is a separate "bus".
 * Multiple slaves can share one bus — they each have their own CS pin.
 *
 * This struct has two kinds of data:
 *   1. CONFIGURATION (set once at init, never changes):
 *      cpol, cpha, data_size, first_bit, baud_prescaler
 *
 *   2. RUNTIME STATE (changes during operation):
 *      slave_count, busy, slaves[]
 *
 * POINTER PATTERN:
 * We always pass this as a POINTER (SPI_Bus_t *bus), not by value.
 * If we passed by value, C would copy the entire struct every function call.
 * That's wasteful and also means changes inside the function wouldn't
 * affect the original. Pointers avoid the copy and allow modification.
 *
 * USAGE EXAMPLE:
 *   SPI_Bus_t my_bus;
 *   my_bus.bus_index  = 0;        // → maps to SPI1 in get_hal_handle()
 *   my_bus.cpol       = SPI_CPOL_LOW;
 *   my_bus.cpha       = SPI_CPHA_2EDGE;  // Mode 1 for ADS1220
 *   my_bus.data_size  = SPI_DATASIZE_8BIT;
 *   my_bus.first_bit  = SPI_FIRSTBIT_MSB;
 *   SPI_InitBus(&my_bus);         // pass ADDRESS of the struct (&)
 * ----------------------------------------------------------------------------- */
typedef struct {
    uint8_t           bus_index;        /* 0 = SPI1, 1 = SPI3, etc.
                                         * Used inside the driver to look up the
                                         * correct HAL handle (hspi1, hspi3, ...)      */

    SPI_MasterSlave_t master_slave;     /* Almost always SPI_MODE_MASTER               */

    SPI_CPOL_t        cpol;             /* Clock polarity — see enum above              */

    SPI_CPHA_t        cpha;             /* Clock phase — see enum above
                                         * ADS1220: SPI_CPHA_2EDGE                      */

    SPI_DataSize_t    data_size;        /* 8-bit for ADS1220                            */

    SPI_FirstBit_t    first_bit;        /* MSB first for ADS1220                        */

    uint32_t          baud_prescaler;   /* Divides the APB clock to set SPI speed.
                                         * Example: if APB = 84MHz and prescaler = 16,
                                         *   SPI clock = 84/16 = 5.25 MHz
                                         * ADS1220 max: 4MHz at 5V, 2MHz at 3.3V
                                         * Use STM32 HAL constants:
                                         *   SPI_BAUDRATEPRESCALER_16
                                         *   SPI_BAUDRATEPRESCALER_32, etc.             */

    uint8_t           slave_count;      /* How many slaves have been registered so far.
                                         * Starts at 0, incremented by RegisterSlave().
                                         * Used as the index for the next empty slot.   */

    uint8_t           busy;             /* Bus lock flag.
                                         * 0 = bus is free, accept transfers
                                         * 1 = transfer in progress, reject new calls
                                         * This prevents two parts of your code from
                                         * simultaneously trying to use the same bus.
                                         * In an RTOS you'd replace this with a mutex.  */

    SPI_Slave_t       slaves[SPI_MAX_SLAVES]; /* Static array of slave descriptors.
                                               * "Static" here means fixed-size at
                                               * compile time — no malloc needed.
                                               * SPI_MAX_SLAVES = 4, so this reserves
                                               * space for 4 slaves per bus.
                                               * Indexed 0..slave_count-1 are valid.    */
} SPI_Bus_t;


/* -----------------------------------------------------------------------------
 * SPI_Transfer_t — describes ONE transfer transaction
 * -----------------------------------------------------------------------------
 * This is a TEMPORARY struct — you create it on the stack just before calling
 * SPI_Transfer(), pass it in, and it's done. It's not stored permanently.
 *
 * WHY A STRUCT INSTEAD OF FUNCTION PARAMETERS?
 * We could have written:
 *   SPI_Status_t SPI_Transfer(SPI_Bus_t*, SPI_Command_t, uint8_t*, uint8_t*, uint16_t, uint8_t);
 * But that's 6 parameters — hard to read, easy to mix up order.
 * A struct is self-documenting: .tx_buf = ... is obvious.
 * Also easy to extend later without changing the function signature.
 *
 * USAGE EXAMPLES:
 *
 * 1) Send one command byte (ADS1220 RESET):
 *   uint8_t cmd = 0x06;
 *   SPI_Transfer_t xfer = {
 *       .command     = SPI_CMD_TX,
 *       .tx_buf      = &cmd,   // pointer to our byte
 *       .rx_buf      = NULL,   // we don't care what comes back
 *       .length      = 1,
 *       .slave_index = ads_idx,
 *   };
 *   SPI_Transfer(&my_bus, &xfer);
 *
 * 2) Read 3 bytes of ADC data (RDATA command):
 *   uint8_t tx[4] = {0x10, 0x00, 0x00, 0x00}; // RDATA + 3 dummy bytes
 *   uint8_t rx[4] = {0};
 *   SPI_Transfer_t xfer = {
 *       .command     = SPI_CMD_TX_RX,
 *       .tx_buf      = tx,
 *       .rx_buf      = rx,
 *       .length      = 4,
 *       .slave_index = ads_idx,
 *   };
 *   SPI_Transfer(&my_bus, &xfer);
 *   // Now rx[1], rx[2], rx[3] contain the 24-bit ADC result
 * ----------------------------------------------------------------------------- */
typedef struct {
    SPI_Command_t command;       /* What kind of transfer: TX, RX, or TX_RX?         */

    uint8_t      *tx_buf;        /* Pointer to the data we want to SEND.
                                  * Must point to a valid buffer if command is TX/TX_RX.
                                  * Can be NULL if command is RX-only.
                                  * uint8_t* means "pointer to byte(s)" — the length
                                  * field tells us how many bytes to use.             */

    uint8_t      *rx_buf;        /* Pointer to buffer where RECEIVED data will be stored.
                                  * Must point to a valid buffer if command is RX/TX_RX.
                                  * Can be NULL if command is TX-only.
                                  * The caller must allocate this buffer before calling. */

    uint16_t      length;        /* How many bytes to transfer.
                                  * tx_buf and rx_buf must each be at least this long.
                                  * uint16_t means up to 65535 bytes — plenty for SPI. */

    uint8_t       slave_index;   /* Which slave on the bus to talk to.
                                  * This is the index returned by SPI_RegisterSlave().
                                  * The driver uses it to look up the CS pin.          */
} SPI_Transfer_t;


/* =============================================================================
 * PUBLIC FUNCTION DECLARATIONS
 * =============================================================================
 * These are "declarations" — they tell the compiler that these functions EXIST
 * and what their signature is. The actual CODE is in spi_driver.c.
 *
 * This is the "contract" of the driver. Any file that includes this header
 * can call these functions.
 *
 * The pattern we follow: all public functions are named SPI_VerbNoun()
 *   SPI_    = prefix, so you know it belongs to this driver
 *   Verb    = what action (Init, Transfer, Register, DeInit)
 *   Noun    = what it acts on (Bus, Slave)
 * ============================================================================= */

/**
 * SPI_InitBus() — First thing you call for each bus.
 *
 * WHEN: Call this in main() AFTER MX_SPI1_Init() (CubeMX init).
 *       CubeMX sets up the hardware registers. We set up our software state.
 *
 * WHAT IT DOES:
 *   - Validates the bus pointer and bus_index
 *   - Clears the slave table (all slots empty)
 *   - Sets busy = 0 (bus is free)
 *   - Copies your config into the global spi_bus[] array
 *
 * PARAMETERS:
 *   bus — pointer to an SPI_Bus_t you filled with your config settings
 *
 * RETURNS: SPI_OK on success, SPI_ERROR if something is wrong
 *          (null pointer, bus_index out of range, no HAL handle found)
 */
SPI_Status_t SPI_InitBus(SPI_Bus_t *bus);

/**
 * SPI_RegisterSlave() — Add a slave device to a bus.
 *
 * WHEN: Call once per slave, after SPI_InitBus().
 *
 * WHAT IT DOES:
 *   - Stores the CS pin and name in the next free slaves[] slot
 *   - Immediately deasserts (drives HIGH) the CS pin
 *     → so the slave starts in a known "not selected" state
 *   - Gives you back the slave's index via slave_idx_out
 *
 * PARAMETERS:
 *   bus           — the bus this slave is on
 *   cs_pin        — GPIO pin constant, e.g. GPIO_PIN_4
 *   desc          — human readable name, e.g. "ADS1220"
 *   slave_idx_out — pointer to uint8_t that will receive the index
 *                   Use this index in every SPI_Transfer_t.slave_index
 *
 * USAGE:
 *   uint8_t ads_index;
 *   SPI_RegisterSlave(&my_bus, GPIO_PIN_4, "ADS1220", &ads_index);
 *   // Now ads_index holds 0 (first slave registered)
 *   // Pass ads_index in xfer.slave_index for all ADS1220 transfers
 */
SPI_Status_t SPI_RegisterSlave(SPI_Bus_t  *bus,
                                uint16_t    cs_pin,
                                const char *desc,
                                uint8_t    *slave_idx_out);

/**
 * SPI_Transfer() — Perform one complete SPI transaction.
 *
 * WHEN: Any time you need to send/receive data to/from a slave.
 *
 * WHAT IT DOES (in order):
 *   1. Validates all inputs (null checks, index bounds, buffer checks)
 *   2. Checks bus is not busy
 *   3. Sets busy = 1
 *   4. Pulls CS pin LOW (selects the slave)
 *   5. Calls HAL to clock out the bytes
 *   6. Pulls CS pin HIGH (deselects — ALWAYS, even on error)
 *   7. Sets busy = 0
 *   8. Returns status
 *
 * PARAMETERS:
 *   bus  — the bus to use
 *   xfer — filled SPI_Transfer_t (see struct comments above for examples)
 *
 * RETURNS: SPI_OK / SPI_ERROR / SPI_BUSY / SPI_TIMEOUT
 *
 * IMPORTANT: After this returns, if command was RX or TX_RX,
 *            your rx_buf contains the received bytes.
 */
SPI_Status_t SPI_Transfer(SPI_Bus_t *bus, SPI_Transfer_t *xfer);

/**
 * SPI_TransferByte() — Send one byte, receive one byte.
 *
 * WHEN: Quick single-byte operations. Useful during bring-up and debugging.
 *       Also used inside ads1220_driver.c for simple command sends.
 *
 * WHAT IT DOES:
 *   Builds a SPI_Transfer_t internally and calls SPI_Transfer().
 *   This is a "convenience wrapper" — same result, less typing.
 *
 * PARAMETERS:
 *   bus          — the bus to use
 *   slave_index  — slave to talk to (from SPI_RegisterSlave)
 *   tx_byte      — the byte to send
 *
 * RETURNS: The byte received from the slave, or 0xFF on error.
 *
 * USAGE:
 *   uint8_t response = SPI_TransferByte(&my_bus, ads_index, 0x06);
 *   // Sends 0x06 (ADS1220 RESET), response is usually don't-care
 */
uint8_t SPI_TransferByte(SPI_Bus_t *bus, uint8_t slave_index, uint8_t tx_byte);

/**
 * SPI_DeInit() — Shut down a bus cleanly.
 *
 * WHEN: Before power-gating the SPI peripheral, or before reconfiguring it.
 *       Not often needed in simple projects, but good practice.
 *
 * WHAT IT DOES:
 *   - Loops through all registered slaves and deasserts their CS pins
 *   - Zeroes out the entire SPI_Bus_t struct (clears all state)
 *
 * After calling this, do NOT use any slave_index values you stored —
 * they are no longer valid. Call SPI_InitBus() + SPI_RegisterSlave() again.
 */
SPI_Status_t SPI_DeInit(SPI_Bus_t *bus);


/* =============================================================================
 * GLOBAL VARIABLE DECLARATION
 * =============================================================================
 * "extern" means: "this variable EXISTS somewhere (in spi_driver.c),
 *  but I'm just declaring it here so other files know it exists."
 *
 * The actual definition (memory allocation) is in spi_driver.c:
 *   SPI_Bus_t spi_bus[SPI_BUS_COUNT];   ← this allocates the memory
 *
 * Other files can access spi_bus[0], spi_bus[1] by including this header.
 *
 * USAGE EXAMPLE in main.c:
 *   #include "spi_driver.h"
 *   // ...
 *   SPI_Bus_t *bus = &spi_bus[0];   // get pointer to bus 0
 *   SPI_Transfer(bus, &xfer);
 *
 * WHY GLOBAL?
 * The bus state (which slaves are registered, busy flag, etc.) needs to
 * persist for the entire lifetime of the program. Local variables would
 * disappear when the function returns. Global arrays persist forever.
 * ============================================================================= */
extern SPI_Bus_t spi_bus[SPI_BUS_COUNT];


/* End of header guard — matches #ifndef SPI_DRIVER_H at the top */
#endif /* SPI_DRIVER_H */